 print("You reluctantly resist the relentless attack...")
 print("You must shield yourself from this menacing individual...")
 print("Let battle commence...")
 print("You are forced to defend yourself...")
 print("You suddenly feel you are under attack and, therefore, must engage in battle...")